<a href="https://colab.research.google.com/github/leonamcassemir0/python-projects/blob/main/machineLearningIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
string = tf.Variable("This is string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)
print(string, number, floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is string'> <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


In [3]:
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [16]:
rank2_tensor.shape

tensor1 = tf.ones([1, 2, 3])
# tensor2 = tf.reshape(tensor1, [2, 3, 1])
# tensor3 = tf.reshape(tensor2, [3, -1])
# print(tensor1)

tensor_t = tf.fill([3, 3, 5], 6)
print(tensor_t)

tf.Tensor(
[[[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]

 [[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]

 [[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]], shape=(3, 3, 5), dtype=int32)
